version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo-notes
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notesdb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
